export const GET_LEADS = 'GET_LEADS'
export const SET_LEADS_DATA = 'SET_LEADS_DATA'
export const LOADING = 'LOADING'
export const ADD_LEAD = 'ADD_LEAD'
export const RESPONSE_MESSAGE = 'RESPONSE_MESSAGE'
export const UPDATE_ERRORS = 'UPDATE_ERRORS'
export const DELETE_LEAD = 'DELETE_LEAD'
export const REFRESH = 'REFRESH'